name: CI

on:
  pull_request:
  push:

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - java: 8
    name: Java v${{ matrix.java }}
    steps:

      - name: Git checkout
        uses: actions/checkout@v2

      - name: Setup Scala
        uses: japgolly/setup-everything-scala@v2.0
        with:
          java-version: adopt@1.${{ matrix.java }}

      - name: Build and test
        shell: bash
        run: sbt test
